version: '2.3'

services:
  postgresql:
    image: sameersbn/postgresql:14-20230628
    environment:
      - DB_USER=redmine
      - DB_PASS=password
      - DB_NAME=redmine_production
    volumes:
      - /srv/docker/redmine/postgresql:/var/lib/postgresql
    healthcheck:
      test: "psql -U postgres"
      interval: 3s
      timeout: 3s
      retries: 5
      start_period: 10s

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CERTBOT_EMAIL=${CERTBOT_EMAIL}
    volumes:
      - /srv/docker/redmine/nginx/conf.d:/etc/nginx/conf.d
      - /srv/docker/redmine/redmine/certs:/etc/ssl/certs
      - /srv/docker/redmine/nginx/logs:/var/log/nginx
    depends_on:
      - postgresql

  redmine:
    build: ./
    image: sameersbn/redmine:5.1.3
    depends_on:
      postgresql:
        condition: service_healthy
      nginx:
        condition: service_started
    environment:
      - TZ=America/Denver

      - DB_ADAPTER=postgresql
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_USER=redmine
      - DB_PASS=password
      - DB_NAME=redmine_production
      - DB_SSL_MODE=prefer

      - REDMINE_PORT=10445
      - REDMINE_HTTPS=true
      # - SSL_KEY_PATH=/home/redmine/data/certs/
      # - SSL_CERTIFICATE_PATH=/home/redmine/data/certs/
      # - SSL_DHPARAM_PATH=/home/redmine/data/certs/

      - REDMINE_SUDO_MODE_ENABLED=false
      - REDMINE_SUDO_MODE_TIMEOUT=15

      - REDMINE_CONCURRENT_UPLOADS=2

      - REDMINE_BACKUP_SCHEDULE=daily
      - REDMINE_BACKUP_EXPIRY=604800
      - REDMINE_BACKUP_TIME=04:00

      - SMTP_ENABLED=false
      - SMTP_METHOD=smtp
      - SMTP_DOMAIN=www.example.com
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=mailer@example.com
      - SMTP_PASS=password
      - SMTP_STARTTLS=true
      - SMTP_AUTHENTICATION=:login

      - IMAP_ENABLED=false
      - IMAP_HOST=imap.gmail.com
      - IMAP_PORT=993
      - IMAP_USER=mailer@example.com
      - IMAP_PASS=password
      - IMAP_SSL=true
      - IMAP_INTERVAL=30

    ports:
      - "10083:80"
      - "10445:443"
    volumes:
      - /srv/docker/redmine/redmine:/home/redmine/data
      - /srv/docker/redmine/redmine-logs:/var/log/redmine
      - /srv/docker/redmine/redmine/certs:/home/redmine/data/certs
